// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkWmIxby90eDmgyqAI2eTVT3WDmVhpEvg',
    appId: '1:809728185233:web:066566190b5b4d54a78030',
    messagingSenderId: '809728185233',
    projectId: 'news-app-5f984',
    authDomain: 'news-app-5f984.firebaseapp.com',
    storageBucket: 'news-app-5f984.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDohvxwFZnRDot_5iX1RDJqFMfDcMT0SY4',
    appId: '1:809728185233:android:ba2c674e4879b7b9a78030',
    messagingSenderId: '809728185233',
    projectId: 'news-app-5f984',
    storageBucket: 'news-app-5f984.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZ7fBJKXjw8_SNsJ8axOwqKJ8TNSsFWe4',
    appId: '1:809728185233:ios:408898c9929765a8a78030',
    messagingSenderId: '809728185233',
    projectId: 'news-app-5f984',
    storageBucket: 'news-app-5f984.appspot.com',
    iosClientId: '809728185233-v0lik8orihbnol0mn61gkoqi74405ovv.apps.googleusercontent.com',
    iosBundleId: 'com.example.newsBlogApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZ7fBJKXjw8_SNsJ8axOwqKJ8TNSsFWe4',
    appId: '1:809728185233:ios:ffdf3171ecf3f2e8a78030',
    messagingSenderId: '809728185233',
    projectId: 'news-app-5f984',
    storageBucket: 'news-app-5f984.appspot.com',
    iosClientId: '809728185233-rr3cbbtmfodcgvnpvedofbmo3c17p9s9.apps.googleusercontent.com',
    iosBundleId: 'com.example.newsBlogApp.RunnerTests',
  );
}
